### ISSUE TITLE
怎么给tableView每个cell新增UIPreviewAction呢？

### ISSUE THREAD

**Issue by qqcc1388** [Hyman00/YJ3DTouch#1]
用下面的方式只有touch效果，没有Action效果
YJ3DTouchConfig *actionItemConfig = [YJ3DTouchConfig new];
actionItemConfig.navigation = self.navigationController;
//actionItemConfig.clickActionTarget = self;
//actionItemConfig.clickAction = @selector(actionItemsBtnTap);
    
UIPreviewAction *action1 = [UIPreviewAction actionWithTitle:@"action1"
                                                      style:UIPreviewActionStyleDefault
                                                    handler:^(UIPreviewAction * _Nonnull action, UIViewController * _Nonnull previewViewController) {
                                                            NSLog(@"action1");
                                                    }];
UIPreviewAction *action2 = [UIPreviewAction actionWithTitle:@"action2"
                                                      style:UIPreviewActionStyleDefault
                                                    handler:^(UIPreviewAction * _Nonnull action, UIViewController * _Nonnull previewViewController) {
                                                            NSLog(@"action2");
                                                    }];
actionItemConfig.previewActionItems = @[action1, action2];
[self yj_active3DTouchView:self.tableView touchConfig:actionItemConfig];

**Comment by Hyman00** [comment]
First, thank you for pointing out this question. Now, It has been fixed.

However, if you want to specify an action for each cell, you can use  "yj_active3DTouchView:touchConfig:" to active 3D Touch for UITableViewCell or UICollectionViewCell. However, you can no longer use the "yj_active3DTouchTable:forNavigation:" or "yj_active3DTouchCollectionView:forNavigation:" method.
